//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalMomento3.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FinalMomento3.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Camera.
        /// </summary>
        internal static string Camara {
            get {
                return ResourceManager.GetString("Camara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quantity Of Products: .
        /// </summary>
        internal static string CantidadDeProductos {
            get {
                return ResourceManager.GetString("CantidadDeProductos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Purchase.
        /// </summary>
        internal static string Compra {
            get {
                return ResourceManager.GetString("Compra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buy Process.
        /// </summary>
        internal static string CompraEnProceso {
            get {
                return ResourceManager.GetString("CompraEnProceso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm Purchase.
        /// </summary>
        internal static string ConfirmarCompra {
            get {
                return ResourceManager.GetString("ConfirmarCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Continue.
        /// </summary>
        internal static string Continuar {
            get {
                return ResourceManager.GetString("Continuar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        internal static string Contraseña {
            get {
                return ResourceManager.GetString("Contraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Description: .
        /// </summary>
        internal static string Descripcion {
            get {
                return ResourceManager.GetString("Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Product Description: .
        /// </summary>
        internal static string DescripcionDelProducto {
            get {
                return ResourceManager.GetString("DescripcionDelProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The User And/Or Password Is Not Allowed.
        /// </summary>
        internal static string ElUsuarioYOContraseñaNoEsPermitido {
            get {
                return ResourceManager.GetString("ElUsuarioYOContraseñaNoEsPermitido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Purchase information.
        /// </summary>
        internal static string InformacionDeCompra {
            get {
                return ResourceManager.GetString("InformacionDeCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter.
        /// </summary>
        internal static string Ingresar {
            get {
                return ResourceManager.GetString("Ingresar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log In.
        /// </summary>
        internal static string Ingreso {
            get {
                return ResourceManager.GetString("Ingreso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Purchase Is Properly Generated.
        /// </summary>
        internal static string LaCompraSeAhGeneradoCorrectamente {
            get {
                return ResourceManager.GetString("LaCompraSeAhGeneradoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name: .
        /// </summary>
        internal static string Nombre {
            get {
                return ResourceManager.GetString("Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Price: .
        /// </summary>
        internal static string Precio {
            get {
                return ResourceManager.GetString("Precio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Price Of The Product: .
        /// </summary>
        internal static string PrecioDelProducto {
            get {
                return ResourceManager.GetString("PrecioDelProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Product: .
        /// </summary>
        internal static string Producto {
            get {
                return ResourceManager.GetString("Producto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Products.
        /// </summary>
        internal static string Productos {
            get {
                return ResourceManager.GetString("Productos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reference: .
        /// </summary>
        internal static string Referencia {
            get {
                return ResourceManager.GetString("Referencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Take Photo.
        /// </summary>
        internal static string TomarFoto {
            get {
                return ResourceManager.GetString("TomarFoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Take Video.
        /// </summary>
        internal static string TomarVideo {
            get {
                return ResourceManager.GetString("TomarVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Totality: .
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username: .
        /// </summary>
        internal static string Usuario {
            get {
                return ResourceManager.GetString("Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You Must Enter The Password.
        /// </summary>
        internal static string ValidacionContraseña {
            get {
                return ResourceManager.GetString("ValidacionContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You Must Enter The Username.
        /// </summary>
        internal static string ValidacionUsuario {
            get {
                return ResourceManager.GetString("ValidacionUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pick Photo.
        /// </summary>
        internal static string VerFoto {
            get {
                return ResourceManager.GetString("VerFoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pick Video.
        /// </summary>
        internal static string VerVideo {
            get {
                return ResourceManager.GetString("VerVideo", resourceCulture);
            }
        }
    }
}
